I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/characters/characters.rpy", line 3, in script
    define candy = Character(
  File "game/characters/characters.rpy", line 3, in script
    define candy = Character(
  File "game/characters/characters.rpy", line 6, in <module>
    callback=beep,
NameError: name 'beep' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/cpu/renpy8/renpy/bootstrap.py", line 274, in bootstrap
    renpy.main.main()
  File "/home/cpu/renpy8/renpy/main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/characters/characters.rpy", line 3, in script
    define candy = Character(
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/characters/characters.rpy", line 3, in script
    define candy = Character(
  File "/home/cpu/renpy8/renpy/ast.py", line 2441, in execute
    self.set()
  File "/home/cpu/renpy8/renpy/ast.py", line 2455, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/home/cpu/renpy8/renpy/python.py", line 1073, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/characters/characters.rpy", line 6, in <module>
    callback=beep,
NameError: name 'beep' is not defined

Linux-5.19.9-arch1-1-x86_64-with-glibc2.36 x86_64
Ren'Py 8.0.1.22070801
ptagain 1.0
Thu Sep 29 21:39:31 2022
